# --- Color Scheme ---
# Corrected path to point inside the themes folder
include themes/mocha.conf

# --- Transparency ---
# This must be BELOW the include to overwrite the theme's background
background_opacity 0.75
dynamic_background_opacity yes

# --- Window Layout ---
# Increased padding slightly for a cleaner look with rounded corners
window_padding_width 0
placement_strategy center

# --- Advanced ---
# Removes any potential graphical glitches in the margins
window_margin_width 5
single_window_margin_width 5
# font_family OperatorMono Nerd Font


# BEGIN_KITTY_FONTS
font_family      family='OperatorMono Nerd Font' postscript_name=OperatorMonoNerdFontComplete-Medium
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
#
font_size 11.0
#
symbol_map U+1F600-U+1F64F Noto Color Emoji
