#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DP-2  --primary --mode 2560x1440 --rate 165.00 --pos 0x0 --rotate normal \
       --output DP-4 --mode 2560x1440 --rate 165.00 --pos 2560x0 --rotate normal

bspc monitor DP-4 -d 1 3 4 5 6 7
bspc monitor DP-2 -d 2

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config tight_gestures true

# Colores de los bordes (Mocha)
bspc config normal_border_color  "#45475a"
bspc config active_border_color  "#b4befe"
bspc config focused_border_color "#b4befe"
bspc config presel_feedback_color "#f5e0dc"

# Configuración visual
bspc config border_width         2
bspc config window_gap          12

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

nitrogen --restore &
eww open-many bar_primary bar_secondary &
picom -b &
greenclip daemon &
xrdb -merge ~/.Xresources &
xsetroot -cursor_name left_ptr &

killall -q dunst

(sleep 2 && /usr/bin/dunst) &
